name: Feature Request
description: Suggest an idea for REMPO
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### 💡 Have a great idea?
        We'd love to hear about how we can make REMPO better for you.
  - type: textarea
    id: idea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
